name: Heartsteal
main: me.verxus.heartsteal.HeartstealPlugin
version: 1.1
api-version: 1.12
description: Heartsteal plugin for 1.12.2

commands:
  withdraw:
    description: Withdraws a heart to give or store for later.
    usage: /withdraw
  info:
    description: Tells the version info and the creator of the plugin.
    usage: /info
  giveheart:
      description: Gives a player a heart via admin,
      usage: /giveheart <player> <amount>